Init
Teaching-projects/-SZE-MOSZE-2020-My_Little_D-D--CLOSED pull request #1
Opened 2020-09-15 04:11 UTC by RaboczkiCsongor

Első feladat leadás

2020-09-15 14:32 UTC, hegyhati requested changes

2020-09-15 14:32 UTC, hegyhati commented on Unit.cpp
> +}
warum?

2020-09-15 14:32 UTC, hegyhati commented on Unit.cpp
> +    Health = Health - amount;
-=?

2020-09-15 14:32 UTC, hegyhati commented on Unit.h
> +};
I find the lack of consts very disturbing.

2020-09-15 14:32 UTC, hegyhati commented on Unit.h
> +};
Illetve a setHealth tul altalanos, nem akarjuk, hogy akarki akarmikor akarmire beallithassa. Csak ha egy masik unit meguti, akkor annak a damage-evel csokkenjen.

2020-09-15 14:32 UTC, hegyhati commented on main.cpp
> +void printUnits(Unit* UnitA, Unit* UnitB){
miert pointer?

2020-09-15 14:32 UTC, hegyhati commented on main.cpp
> +void printUnits(Unit* UnitA, Unit* UnitB){
also, const?

2020-09-15 14:32 UTC, hegyhati commented on main.cpp
> +    Unit* UnitTwo = new Unit(argv[4],argv[5],argv[6]);
Miert dinamikusan?

2020-09-16 06:58 UTC, RaboczkiCsongor commented
@hegyhati megcsináltuk a kért módositásokat

2020-09-16 22:46 UTC, hegyhati requested changes
Par aprosag, az az attack signatura az egyetlen komolyabb modositas, meg a konstruktort tisztazzatok le.

2020-09-16 22:46 UTC, hegyhati commented on Unit.cpp
> +}
Sokkal tisztabb volna, ha int/double-oket var a numerikus adatokert a konstruktor. A konfertalast pedig kint megoldani egy atoi-vel a mainben es kesz. vagy atof.

2020-09-16 22:46 UTC, hegyhati commented on Unit.cpp
> +void Unit::getAttacked(int amount){
Ne lehessen csak ugy akarmennyivel csokkenteni, csak egy masik unit ha meguti, akkro annak a damage-evel csokkenjen. De nem hivhassam meg csak ugy, hogy na, csokkentsuk 100000-el.

2020-09-16 22:46 UTC, hegyhati commented on main.cpp
> +void const printUnits(Unit UnitA, Unit UnitB) {
biztos le akarod masolni oket ahhoz, hogy kiird?

2020-09-16 22:46 UTC, hegyhati commented on main.cpp
> +void const printUnits(Unit UnitA, Unit UnitB) {
also, const?

2020-09-16 22:46 UTC, hegyhati commented on main.cpp
> +        UnitB.getAttacked(UnitA.getDamage());
A jelen szignaturaval itt akar beirhatsz veletlenul 2*UnitA.getDamage()-et is. Az ilyen hibakat volna jo elkerulni.(tobbek kozott)

2020-09-17 07:08 UTC, RaboczkiCsongor commented
@hegyhati Elkészültek a kér javítások

2020-09-18 08:34 UTC, hegyhati requested changes
Ket aprosag, aztan rendben.

2020-09-18 08:34 UTC, hegyhati commented on Unit.cpp
> +void Unit::getAttacked(Unit& unitAttacker){
ide is elferne megy egy const.

2020-09-18 08:34 UTC, hegyhati commented on main.cpp
> +void const printUnits(const Unit& UnitA,const Unit& UnitB) {
jajj, ezt a void const-ot honnet szeditek?

2020-09-18 15:37 UTC, RaboczkiCsongor commented
@hegyhati Elkészültek a kért módosítások. A void const nem szándékos, félre copy-zott const volt, amit nem vettem észre. Elnézést kérek!

2020-09-21 14:15 UTC, hegyhati approved these changes

2020-09-21 14:15 UTC, merged